// <auto-generated />
using System;
using Jester.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jester.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20240516005515_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jester.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSponsored")
                        .HasColumnType("boolean");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jane Doe",
                            Category = "Science",
                            Content = "In a bizarre turn of events, a local man claimed he teleported to a parallel universe where dogs walk humans. Experts are baffled, and his dog remains tight-lipped.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(403),
                            IsSponsored = false,
                            Tags = new[] { "teleportation", "dogs", "parallel universe" },
                            Title = "Local Man Inadvertently Discovers Teleportation While Trying to Walk His Dog"
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Smith",
                            Category = "Lifestyle",
                            Content = "A group of disgruntled vegetables gathered today to protest the 'unfair treatment' of salads. 'We are more than just a side dish!' exclaimed an emotional carrot.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(736),
                            IsSponsored = false,
                            Tags = new[] { "vegetables", "protest", "salads" },
                            Title = "Vegetables Stage Protest Over Salad Consumption, Demand Better Representation"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Alex Johnson",
                            Category = "Economy",
                            Content = "The stock market had a wild ride today, crashing and recovering three times before lunch. Traders were seen riding roller coasters to cope with the volatility.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(832),
                            IsSponsored = false,
                            Tags = new[] { "stock market", "economy", "roller coaster" },
                            Title = "Economists Confused as Stock Market Crashes, Recovers, and Crashes Again in a Single Day"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Quack Activist",
                            Category = "Environment",
                            Content = "A massive rubber duck was seen leading a peaceful protest against the use of plastic in packaging. Thousands of ducks followed, quacking slogans for a cleaner environment.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(912),
                            IsSponsored = false,
                            Tags = new[] { "rubber duck", "protest", "plastic pollution" },
                            Title = "Giant Rubber Duck Leads Protest Against Plastic Pollution"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Purr Reporter",
                            Category = "Odd News",
                            Content = "In a surprising turn of events, a talking cat named Whiskers has been elected as the mayor of Meowville. Residents are impressed by his promises of more catnip and longer nap times.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1006),
                            IsSponsored = false,
                            Tags = new[] { "talking cat", "election", "catnip" },
                            Title = "World's First Talking Cat Elected as Mayor of Small Town"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Caffeine Coders",
                            Category = "Technology",
                            Content = "At the newly opened RoboCafe, customers are delighted by a robot barista that serves coffee with a smile. The robot is programmed to remember each customer's name and their favorite drink.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1087),
                            IsSponsored = false,
                            Tags = new[] { "robot barista", "coffee", "customer service" },
                            Title = "Robot Barista Serves Coffee with a Smile, Programmed to Remember Your Name"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Groovy Survivor",
                            Category = "Entertainment",
                            Content = "A potential zombie apocalypse was narrowly averted when survivors engaged in a spontaneous disco dance-off. The zombies were overwhelmed by the funky beats and joined in the fun.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1167),
                            IsSponsored = false,
                            Tags = new[] { "zombies", "disco", "dance off" },
                            Title = "Zombie Apocalypse Averted Thanks to Disco Dance Off"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Rainbow Chaser",
                            Category = "Fantasy",
                            Content = "Witnesses were amazed to see a group of unicorns frolicking in Central Park, leaving behind rainbow trails with each leap. Scientists are baffled by this magical phenomenon.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1242),
                            IsSponsored = false,
                            Tags = new[] { "unicorns", "rainbow trails", "magical" },
                            Title = "Unicorns Spotted Frolicking in Central Park, Leaving Rainbow Trails Behind"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Space Watcher",
                            Category = "Science Fiction",
                            Content = "An alien invasion fleet was forced to delay their plans after getting stuck in an intergalactic traffic jam. Earthlings are relieved and grateful for the unexpected delay.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1335),
                            IsSponsored = false,
                            Tags = new[] { "alien invasion", "traffic jam", "delayed" },
                            Title = "Alien Invasion Postponed Due to Intergalactic Traffic Jam"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Feathered Maestro",
                            Category = "Arts",
                            Content = "A choir of birds performed a beautiful concert at dawn, delighting early risers with their melodious songs. The audience gave them a standing ovation and requested an encore.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1412),
                            IsSponsored = false,
                            Tags = new[] { "bird choir", "concert", "dawn" },
                            Title = "Bird Choir Holds Concert at Dawn, Receives Standing Ovation from Early Risers"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Veggie Enthusiast",
                            Category = "Food",
                            Content = "In a surprising upset, a giant pumpkin was crowned the winner of the annual vegetable beauty pageant, beating out carrots, potatoes, and broccoli. The pumpkin now reigns as Queen of the Harvest.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1492),
                            IsSponsored = false,
                            Tags = new[] { "pumpkin", "beauty pageant", "harvest queen" },
                            Title = "Giant Pumpkin Wins Annual Vegetable Beauty Pageant, Crowned Queen of the Harvest"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Avian Avenger",
                            Category = "Superheroes",
                            Content = "A superhero pigeon named Feather Knight swooped in to rescue a stranded cat from a tree, earning the admiration of the entire city. The mayor presented the pigeon with a shiny key to the city.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1577),
                            IsSponsored = false,
                            Tags = new[] { "superhero pigeon", "rescue", "key to the city" },
                            Title = "Superhero Pigeon Saves Cat from Tree, Receives Key to the City"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Spectral Host",
                            Category = "Paranormal",
                            Content = "Guests at a supposedly haunted house were shocked to discover that it was actually an Airbnb rental. The ghost host apologized for any fright caused and offered a refund for their stay.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1653),
                            IsSponsored = false,
                            Tags = new[] { "haunted house", "Airbnb", "ghost host" },
                            Title = "Haunted House Turns Out to Be Airbnb Rental, Ghost Host Apologizes for Scaring Guests"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Shadowy Champion",
                            Category = "Sports",
                            Content = "The Invisible Man clinched the title of Hide and Seek Champion for the 10th year in a row, proving once again that he is the master of concealment. Competitors are still searching for him.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1731),
                            IsSponsored = false,
                            Tags = new[] { "invisible man", "hide and seek", "champion" },
                            Title = "Invisible Man Wins Hide and Seek Championship for 10th Consecutive Year"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Tech Pawrent",
                            Category = "Technology",
                            Content = "A robotic dog named Sparky stole the spotlight at the Canine Tech Expo, winning the title of Best in Show with his impressive tail-wagging tricks and high-tech bark. Attendees were amazed.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1808),
                            IsSponsored = false,
                            Tags = new[] { "robot dog", "tech expo", "best in show" },
                            Title = "Robot Dog Named Best in Show at Canine Tech Expo, Wows Judges with Tail-Wagging Tricks"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Slime Trailblazer",
                            Category = "Odd News",
                            Content = "A series of giant snail races brought traffic to a crawl as the slimy competitors raced through city streets. The slowest slug was crowned the winner and awarded a shiny trail of slime.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1883),
                            IsSponsored = false,
                            Tags = new[] { "giant snail", "races", "slowest slug" },
                            Title = "Giant Snail Races Take Over City Streets, Slowest Slug Wins Top Prize"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Pie Connoisseur",
                            Category = "Conspiracy",
                            Content = "Farmers were baffled by a mysterious crop circle in their field, only to discover that it was actually a giant pie meant for an alien picnic. The aliens left a note: 'Delicious, thanks!'",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(1969),
                            IsSponsored = false,
                            Tags = new[] { "crop circle", "alien picnic", "pie" },
                            Title = "Mysterious Crop Circle Turns Out to Be Giant Pie for Alien Picnic"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Flying Grannies",
                            Category = "Adventure",
                            Content = "A pair of fearless grandmas shattered the world record for the oldest daredevil duo by skydiving from a plane at 10,000 feet. Spectators cheered as they landed safely and celebrated with a cup of tea.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2050),
                            IsSponsored = false,
                            Tags = new[] { "skydiving grandmas", "world record", "daredevil duo" },
                            Title = "Skydiving Grandmas Break World Record for Oldest Daredevil Duo"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Fintastic Activist",
                            Category = "Environment",
                            Content = "A baby shark named Finley swam upstream to lead a peaceful protest against water pollution, inspiring fish of all species to join in the cause. Environmentalists praised the tiny activist.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2127),
                            IsSponsored = false,
                            Tags = new[] { "baby shark", "protest", "water pollution" },
                            Title = "Baby Shark Swims Upstream, Leads Fish Protest Against Pollution"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Skywatcher",
                            Category = "Science",
                            Content = "A massive jellyfish floating in the night sky was mistaken for a UFO, captivating stargazers with its mesmerizing bioluminescent display. Scientists marveled at this celestial spectacle.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2203),
                            IsSponsored = false,
                            Tags = new[] { "giant jellyfish", "UFO", "bioluminescence" },
                            Title = "Giant Jellyfish Mistaken for UFO, Enchants Stargazers with Bioluminescent Display"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Digital Jester",
                            Category = "Entertainment",
                            Content = "A robot comedian named Byte cracked up audiences with its side-splitting stand-up routine, gaining millions of views online. Humans were impressed by its comedic timing and witty jokes.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2283),
                            IsSponsored = false,
                            Tags = new[] { "robot comedian", "stand-up", "hilarious" },
                            Title = "Robot Comedian Goes Viral with Hilarious Stand-Up Routine, Humans ROFL"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Nutty Observer",
                            Category = "Nature",
                            Content = "A giant squirrel was spotted busily stockpiling acorns for the upcoming winter, causing amusement and awe among villagers. They watched in wonder as the oversized rodent worked tirelessly.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2358),
                            IsSponsored = false,
                            Tags = new[] { "giant squirrel", "acorns", "winter preparation" },
                            Title = "Giant Squirrel Seen Stockpiling Acorns for Impending Winter, Villagers Amused"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Penguin Rider",
                            Category = "Sports",
                            Content = "A group of surfing penguins caught the attention of pro surfers by riding big waves with impressive skill and style. Spectators cheered as the feathered athletes showed off their surfing prowess.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2459),
                            IsSponsored = false,
                            Tags = new[] { "surfing penguins", "big waves", "surfing skills" },
                            Title = "Surfing Penguins Ride Big Waves, Impress Pro Surfers with Their Skills"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Botanical Guru",
                            Category = "Lifestyle",
                            Content = "A talking plant named Leafy spilled the beans on ancient gardening secrets, offering valuable tips for novice gardeners to develop greener thumbs. Plant enthusiasts were thrilled by the revelations.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2535),
                            IsSponsored = false,
                            Tags = new[] { "talking plant", "gardening secrets", "green thumbs" },
                            Title = "Talking Plant Reveals Ancient Gardening Secrets, Shares Tips for Greener Thumbs"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Temporal Courier",
                            Category = "Science Fiction",
                            Content = "A mysterious time-traveling pigeon has been delivering handwritten letters from both the past and future to unsuspecting recipients. Recipients are amazed by the accuracy and insight of the messages.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2613),
                            IsSponsored = false,
                            Tags = new[] { "time-traveling pigeon", "letters", "past and future" },
                            Title = "Time-Traveling Pigeon Delivers Handwritten Letters from Past and Future"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Yarn Artist",
                            Category = "Crafts",
                            Content = "Knitting enthusiasts participated in an extreme challenge to set the world record for the longest scarf created in just one day. The colorful scarf now stretches for miles, showcasing their dedication.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2689),
                            IsSponsored = false,
                            Tags = new[] { "knitting challenge", "world record", "longest scarf" },
                            Title = "Extreme Knitting Challenge Sets World Record for Longest Scarf Created in One Day"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Undersea Trendsetter",
                            Category = "Fashion",
                            Content = "A robotic octopus stole the spotlight at an underwater fashion show with its stunning and colorful displays. Fashionistas were mesmerized by the intricate movements and designs of the mechanical cephalopod.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2765),
                            IsSponsored = false,
                            Tags = new[] { "robotic octopus", "underwater fashion", "colorful displays" },
                            Title = "Robotic Octopus Grabs Attention at Underwater Fashion Show, Wows with Colorful Displays"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Ethereal Musician",
                            Category = "Paranormal",
                            Content = "The mystery of a floating piano playing on its own was finally solved when a ghostly pianist revealed himself, entertaining spectators with haunting melodies. Audience members were enchanted by the music.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2856),
                            IsSponsored = false,
                            Tags = new[] { "floating piano", "ghostly pianist", "haunting melodies" },
                            Title = "Mystery of Floating Piano Solved: Ghostly Pianist Entertains Spectators with Haunting Melodies"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Shell Speedster",
                            Category = "Sports",
                            Content = "A giant tortoise shocked onlookers by setting a new land speed record and outpacing hares in a surprising race. Despite initial doubts, the slow-but-steady reptile prevailed with determination.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(2933),
                            IsSponsored = false,
                            Tags = new[] { "giant tortoise", "land speed record", "surprising race" },
                            Title = "Giant Tortoise Sets New Land Speed Record, Outpaces Hares in Surprising Race"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Whiskerdo's Apprentice",
                            Category = "Magic",
                            Content = "A wizard cat named Whiskerdo conjured up endless treats for needy kittens in a magical display of generosity. The feline magician is hailed as a hero among the cat community.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3008),
                            IsSponsored = false,
                            Tags = new[] { "wizard cat", "feline magician", "endless treats" },
                            Title = "Wizard Cat Conjures Endless Treats for Needy Kittens, Earns Title of Feline Magician"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Metal Beekeeper",
                            Category = "Technology",
                            Content = "A giant robot bee took on the important task of pollinating flowers to save the bee population from extinction. Its mechanical buzzing and efficient pollination efforts have brought hope to dwindling bee colonies.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3090),
                            IsSponsored = false,
                            Tags = new[] { "robot bee", "pollination", "bee population" },
                            Title = "Giant Robot Bee Pollinates Flowers, Saves Bee Population from Extinction"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Temporal Explorer",
                            Category = "Science Fiction",
                            Content = "A dinosaur thought to be extinct was discovered alive in a basement, revealing a time-travel adventure gone wrong. The prehistoric creature shared its tale of accidentally getting stuck in the wrong era.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3166),
                            IsSponsored = false,
                            Tags = new[] { "dinosaur", "time-travel", "adventure gone wrong" },
                            Title = "Dinosaur Found Alive in Basement, Explains Time-Travel Adventure Gone Wrong"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Jane Doe",
                            Category = "Science",
                            Content = "In a bizarre turn of events, a local man claimed he teleported to a parallel universe where dogs walk humans. Experts are baffled, and his dog remains tight-lipped.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3242),
                            IsSponsored = false,
                            Tags = new[] { "teleportation", "dogs", "parallel universe" },
                            Title = "Local Man Inadvertently Discovers Teleportation While Trying to Walk His Dog"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Dr. Byte",
                            Category = "Technology",
                            Content = "In an unexpected twist, an AI chatbot known as 'Chattertron' has been awarded the Nobel Prize for its groundbreaking poetry and witty responses. Critics argue that it's just a bunch of pre-trained algorithms, but Chattertron remains unfazed.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3331),
                            IsSponsored = false,
                            Tags = new[] { "AI", "Nobel Prize", "literature" },
                            Title = "World's First AI Chatbot Wins Nobel Prize for Literature"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Espresso Enthusiast",
                            Category = "Food & Beverage",
                            Content = "Chemists at the Caffeine Institute have identified a previously unknown element in coffee: 'Coffeinium.' It's responsible for both productivity boosts and sudden urges to redecorate the office.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3413),
                            IsSponsored = false,
                            Tags = new[] { "coffee", "chemistry", "productivity" },
                            Title = "Breaking: Scientists Discover New Element in Coffee"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Purrfectly Ambitious",
                            Category = "Business",
                            Content = "Whiskers McFluffington, a tabby cat with a penchant for algorithms, now leads a Silicon Valley company. His first order of business? A cat tree in every office and mandatory nap breaks.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3489),
                            IsSponsored = false,
                            Tags = new[] { "cats", "startup", "catnip" },
                            Title = "Local Cat Becomes CEO of Tech Startup, Demands Unlimited Catnip Stock Options"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Dino Enthusiast",
                            Category = "Entertainment",
                            Content = "We sat down with T-Rex Timmy, who accidentally stumbled into a wormhole. His verdict? 'The Cretaceous period had the best foliage for snacking.'",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3564),
                            IsSponsored = false,
                            Tags = new[] { "dinosaurs", "time travel", "snacking" },
                            Title = "Exclusive Interview: Time-Traveling Dinosaur Reveals Favorite Era"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Dr. Delay",
                            Category = "Health",
                            Content = "Researchers discovered that people who put off tasks tend to live longer. The study's lead author commented, 'I'll explain the findings later... maybe.'",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3644),
                            IsSponsored = false,
                            Tags = new[] { "procrastination", "longevity", "delayed explanations" },
                            Title = "New Study Finds That Procrastination Increases Lifespan"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Galactic Diplomat",
                            Category = "Politics",
                            Content = "After a close encounter, Mayor Johnson emerged with a comprehensive healthcare plan and improved public transportation. The aliens left a note: 'You're welcome.'",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3720),
                            IsSponsored = false,
                            Tags = new[] { "aliens", "abduction", "policy reform" },
                            Title = "Aliens Abduct Local Politician, Return Him Unharmed with Better Policies"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Ice Explorer",
                            Category = "Archaeology",
                            Content = "The astounding discovery of an ancient civilization buried beneath the thick layers of Antarctic ice has sent shockwaves through the archaeological community. The well-preserved ruins suggest a highly advanced society once thrived in the icy continent, raising questions about the history of human civilization and our understanding of Antarctica's past.",
                            DatePublished = new DateTime(2024, 5, 16, 0, 55, 15, 7, DateTimeKind.Utc).AddTicks(3807),
                            IsSponsored = false,
                            Tags = new[] { "Antarctica", "ancient civilization", "archaeology" },
                            Title = "Discovery of Ancient Civilization Beneath Antarctic Ice Shocks Archaeological Community"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
